services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: elearning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '060503'
    ports:
      - '5433:5432'
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data

volumes:
  db-data:
